### ISSUE TITLE
No references found in PAICz reference file

### ISSUE THREAD

**Issue by ehenneken** [adsabs/ADSReferencePipeline#5] opened 2024-04-18 18:38 UTC
According to the log messages in toREFs.log:
```
{"asctime": "2024-04-18T12:00:33.175Z", "name": "toREFs", "processName": "MainProcess", "filename": "toREFs.py", "funcName": "get_references", "levelname": "ERROR", "lineno": 1153, "module": "toREFs", "threadName": "MainThread", "message": "No references found in reference file /proj/ads/references/sources/PAICz/0093/editor.raw.", "timestamp": "2024-04-18T12:00:33.175Z", "hostname": "e81ec4af9250"}
```
However, the file contains reference data:
```
%R 2005PAICz..93....1S
%A Stefl, S.; Rivinius, Th.
%F AA(Astronomical Institute, Academy of Sciences of the Czech Republic, Ondrejo
v) AB(Landessternwarte K&ouml;nigstuhl, 69117 Heidelberg, Germany)
%J Publications of the Astronomical Institute of the Academy of Sciences of the
Czech Republic (ISSN 1211-9105), Vol. 93, p. 1-8
%D 12/2005
%T Be star research by the HEROS group: results from the past decade
%U http://www.asu.cas.cz/PAI/pai93a.pdf
%K Spectroscopy, photometry, Be stars
%B The progress in the investigation of Be stars during the past decade was enab
led mainly thanks to high-resolution echelle spectrographs. Such instruments mad
e possible to carry out multi-line studies of line profile variations and to sea
rch for correlations between photospheric and circumstellar phenomena. The Heros
 team was one of the most active in this field during the last decade.  Here we
summarize the most important achievements reached by the group
%Z
Baade, D., Rivinius, Th., \v{S}tefl, S., Kaufer A., 2002, A\&A, 383, L31~-~L34
Gies, D.G., Bagnuolo, W.G., Ferrara, E.C., et al., 1998, ApJ, 493 440
Hadrava, P., 1995, A\&AS 114, 393
Hadrava, P., 1997, A\&AS 122, 581
Harmanec, P., 1998,  A\&A, .334, 558
Hubert, A.~M.,Floquet, M., 1998,  A\&A, 335, 565
Neiner, C., Henrichs, H.F. Floquet, M., et al., 2003, A\& A, 411, 565
etc etc etc
```
There are other files with the same problem, like e.g. `references/sources/CoKon/0105/CoKon.v105.raw`

**Comment by golnazads** [comment] 2024-09-30 14:37
There is actually no problem in the pipeline. The issue is that per classic these files should be parsed by a latex parser, but they are text references. In the pipeline latex parser expects latex reference file, not text.
@ehenneken If you think these are all text files, I can easily change the mapping in the database for them. Actually there is only 1 PAICz, and it is text. Please check the CoKon and tell me if I should switch them to be processed by text parser, or if we should break them down.

<config journal="CoKon">

  <volume number="DEFAULT">
    <handler type="torefs" name="ADSlatex" publisher="PUBLISHER" suffix="*.raw"/>
  </volume>
</config>

<config journal="PAICz">

  <volume number="DEFAULT">
    <handler type="torefs" name="ADSlatex" publisher="PUBLISHER" suffix="*.raw"/>
  </volume>
</config>


@ehenneken

**Comment by golnazads** [comment] 2024-09-30 14:55
@ehenneken 
OK, so I switched the mapping for PAICz in my local db and it is parsed and resolved with no error. As I suspected the mapping was the issue.
As you can see I made a issue to allow power users to change the mapping if something like this happens. Going to implement that, so that you can actually change them either in your local db or dev db.

**Comment by ehenneken** [comment] 2024-09-30 14:57
Thank you @golnazads

**Closed** 2024-10-21 16:01 UTC
